mustafaenesaksoy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("personalapp.urls"))
]

personalapp/urls.py
from django.urls import path
from . import views

app_name = "personalapp"

urlpatterns = [
    path("",views.index, name="index"),
    path("contact/",views.contact, name="contact")
]

personalapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    message = models.CharField(max_length=200)

    def __str__(self):
        return f"name: {self.name} , email: {self.email}, message: {self.message}"

personalapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models
from django.urls import reverse
from django.contrib import messages


# Create your views here.


def index(request):
    return render(request,"personalapp/index.html")

def contact(request):
    if request.POST:
        name = request.POST["name"]
        email = request.POST["email"]
        message = request.POST["message"]
        models.User.objects.create(name = name,email = email,message = message)
        messages.success(request, 'Mesajınız iletildi!')
        return redirect(reverse("personalapp:index"))
    else:
        return render(request, "personalapp/contact.html")

personalapp/templates/personalapp/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section id="contact" style="text-align: center; margin-top: 50px;">
    <div class="contact-icons">
        <a href="https://www.linkedin.com/in/mustafa-enes-aksoy/" target="_blank" class="icon" ">
            <i class="fab fa-linkedin"></i>
        </a>
        <a href="https://github.com/mustafaenesaksoy" target="_blank" class="icon">
            <i class="fab fa-github"></i>
        </a>
    </div>
</section>

<form action="" method="post" style="margin-top: 70px; margin-left: 50px; margin-right: 40%; margin-bottom: 30px;">
    {% csrf_token %}


    <div class="mb-3">
        <label for="name" class="form-label">Name (required)</label>
        <input type="text" class="form-control" id="name" name="name" required>
      </div>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Email address (required)</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" required>
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Write Your Message</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"  name="message"></textarea>
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

personalapp/templates/personalapp/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}




{% if messages %}
    <ul class="messages">
        {% for message in messages %}
          <div class="notification" id="notification">Your message has been delivered</div>
        {% endfor %}
    </ul>
{% endif %}
<script>
  function showNotification() {
      var notification = document.getElementById("notification");
      notification.classList.add("active");
      setTimeout(function() {
          notification.classList.remove("active");
      }, 3000);
  }
  window.onload = function() {
    showNotification();
};
  </script>

<div class="container marketing">
  <div class="item">
  <div class="row">
    <div class="col-lg-4">
      <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
        <image xlink:href="{% static 'personalapp/word.jpg' %}" width="100%" height="100%" preserveAspectRatio="xMidYMid slice"/> 
      </svg>
      <h2 class="fw-normal">Word Wars</h2>
      <p>Word-finding game from a word list evoking both online and offline words.</p>
      <p><a class="btn btn-secondary" href="https://github.com/mustafaenesaksoy/WordWars">View on GitHub &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
        <image xlink:href="{% static 'personalapp/sports.jpg' %}" width="100%" height="100%" preserveAspectRatio="xMidYMid slice"/> 
      </svg>
      <h2 class="fw-normal">SportsApp</h2>
      <p>A mobile application where you can follow news, fixtures, results, and league standings from various leagues.</p>
      <p><a class="btn btn-secondary" href="https://github.com/mustafaenesaksoy/SportsApp">View on GitHub &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
        <image xlink:href="{% static 'personalapp/imdb.jpg' %}" width="100%" height="100%" preserveAspectRatio="xMidYMid slice"/> 
      </svg>
      <h2 class="fw-normal">IMDBTop100</h2>
      <p>Explore the Greatest Cinematic Gems with Our IMDb Top 100 Films App! </p>
      <p><a class="btn btn-secondary" href="https://github.com/mustafaenesaksoy/IMDBTop10l">View on GitHub &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->
</div>

<p><a class="btn btn-secondary" style="display: block; margin: 0 auto; color:white;  background-color: rgba(93, 15, 15, 0.444);;" href="https://github.com/mustafaenesaksoy/">All my projects &raquo;</a></p>


  <hr class="featurette-divider" style="margin-top: 100px;">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading fw-normal lh-1">Who is <a href="/" style="text-decoration: none; color: rgb(86, 86, 86);">Mustafa Enes Aksoy</a>?</h2>
      <p class="lead" style="margin-top: 30px;">A dedicated individual who is currently pursuing a Bachelor's degree in Computer Engineering at Erzurum Technical University. At the age of 21, he has already developed a strong passion for creating cutting-edge mobile applications.<br><br>

        His journey in the realm of software development has been shaped by a profound fascination with algorithms and their remarkable ability to solve intricate problems. As an aspiring developer, he is committed to pursuing excellence in the field of algorithms. His passion for problem-solving and coding drives him to continuously explore innovative solutions and refine his skills.<br><br>
        
        Currently, he is honing his expertise in mobile application development, deriving immense satisfaction from turning ideas into reality through coding and designing user-friendly interfaces.</p>
    </div>
    <div class="col-md-5">
      <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" style="text-align: center;" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"/><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text>
        <image xlink:href="{% static 'personalapp/my.jpg' %}" width="100%" height="100%" preserveAspectRatio="xMidYMid slice"/> 
      </svg>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette" style="margin-top: 150px; margin-bottom: 50px;">
    <div class="col-md-7 order-md-2">
      <div class="text-and-button">
      <h2 class="featurette-heading fw-normal lh-1">Connect & Contact Me</h2>   
      <p><a class="btn btn-secondary" style="display: flex; margin-left: 100px; width: 50%; color: white; background-color: #662c12;" href="{% url 'personalapp:contact'%}">Contact &raquo;</p></a>
    </div>  
  </div>
  </div>

  <!-- /END THE FEATURETTES -->

</div><!-- /.container -->

</main>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
{% endblock %}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <title>Document</title>

    <style>
      .contact-icons {
            font-size: 40px;
        }
        .contact-icons a {
            margin: 0 20px; 
        }
  .bd-placeholder-img {
    font-size: 10%;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 100%;
    }
  }

  .b-example-divider {
    width: 100%;
    height: 3rem;
    background-color: rgba(0, 0, 0, .1);
    border: solid rgba(0, 0, 0, .15);
    border-width: 1px 0;
    box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
  }

  .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
  }

  .bi {
    vertical-align: -.125em;
    fill: currentColor;
  }

  .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
  }

  .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }

  .btn-bd-primary {
    --bd-violet-bg: #712cf9;
    --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

    --bs-btn-font-weight: 600;
    --bs-btn-color: var(--bs-white);
    --bs-btn-bg: var(--bd-violet-bg);
    --bs-btn-border-color: var(--bd-violet-bg);
    --bs-btn-hover-color: var(--bs-white);
    --bs-btn-hover-bg: #6528e0;
    --bs-btn-hover-border-color: #6528e0;
    --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
    --bs-btn-active-color: var(--bs-btn-hover-color);
    --bs-btn-active-bg: #5a23c8;
    --bs-btn-active-border-color: #5a23c8;
  }
  .bd-mode-toggle {
    z-index: 1500;
  }

  .bold-text {
    font-weight: bold;
    color: white;
    opacity: inherit;
    font-size: x-large;
  }
  
.text-alig {
  top: 50px;
  bottom: auto;
  text-align: center;
}


.item {
  margin-top: 90px;
  margin-bottom: 20px;
  text-align: center;
}
.custom-link {
        color: white;
        text-decoration: none;
        transition: color 0.3s;
    }

    .custom-link:hover {
        color: darkgray;
    }
    .text-and-button {
    display: flex;
}
.carousel-item{
    background-image: url('{% static "personalapp/homepage.jpg" %}');
    background-size: cover;
    background-position: center;
    }

.carousel-caption {
    background-color: rgba(0, 0, 0, 0);
    padding: 20px;
    border-radius: 10px;
  }
  .notification {
    position: fixed;
    top: 10px;
    left: 50%;
    transform: translateX(-50%);
    background-color: rgba(8, 188, 2, 0.8);
    color: white;
    padding: 10px 20px;
    border-radius: 5px;
    opacity: 0;
    visibility: hidden;
    transition: opacity 0.3s, visibility 0.3s;
}

.notification.active {
    opacity: 1;
    visibility: visible;
}
</style>
</head>
<body>
    <main>
        <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel" style="padding: 0; margin: 0;">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <svg class="bd-placeholder-img" width="100%" height="70%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
              <div class="container">
                <div class="carousel-caption text-alig">
                  <a href="/" class="custom-link"><h1>Mustafa Enes Aksoy</h1></a>
                  <p class="opacity-75"><span class="bold-text">Mobile Developer</span></p>
                  <p class="opacity-75">Crafting Innovative Mobile Experiences</p>
                </div>
              </div>
            </div>
          </div>
        </div>

    {% block content %}
    {% endblock %}
</body>
</html>